apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: java-cap-app
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*
  service:
    host: java-cap-app
    name: java-cap-app
    port: 8080