apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-cap-app
spec:
  selector:
    matchLabels:
      templatename: ana-template
  template:
    metadata:
      labels:
        templatename: ana-template
    spec:
      containers:
        - image: anamrzv/java_hana:latest
          name: ana-java-cap-hana-container
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
